# Site settings
title:          Demystifying Tech Leadership
description:    "Some toughts about over 15 years on IT; Sharing learnings about Management and Leadeship"
baseurl:        "/tale"
#url:            "https://chesterhow.github.io"
remote_theme:   chesterhow/tale

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Suzane Sant'Ana
  # url:          https://chester.how
  email:        suzane.santan@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-remote-theme