---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: en/_posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: en
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Español
- type: directory
  path: es/_posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: es
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Data
- type: document
  path: _data/languages.yml
  label: Languages
  match: "**/*"
- type: document
  path: _data/translations.yml
  label: Translations
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
